### ISSUE TITLE
README example lists wrong import

### ISSUE THREAD

**Issue by Ontopic** [unifiedjs/unified-diff#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

*

### Steps to reproduce

import unifiedDiff from 'unifiedDiff'

### Expected behavior

import unifiedDiff from 'unified-diff'

### Actual behavior

import unifiedDiff from 'unifiedDiff'

**Comment by wooorm** [comment]
I think I get what you mean! Would you be interested in helping by making a pull request?
